language: r
sudo: false
cache: packages

r_packages:
  - colorspace

addons:
  apt:
    packages:
    - unixodbc-dev

r-github-packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
